apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapp
  template:
    metadata:
      labels:
        app: userapp
    spec:
      containers:
      - name: userapp
        image: usersapi:1.0
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Host=userdb;Database=users;Username=postgres;Password=postgres"
      volumes:
      - name: pgdata
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: userapp
spec:
  selector:
    app: userapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080