apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menuapp
  template:
    metadata:
      labels:
        app: menuapp
    spec:
      containers:
      - name: menuapp
        image: menuapi:1.0
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Host=db;Database=menu;Username=postgres;Password=postgres"
      volumes:
      - name: pgdata
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: menuapp
spec:
  selector:
    app: menuapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080